### ISSUE TITLE
max file size ?

### ISSUE THREAD

**Issue by maci0** [hoytech/vmtouch#15]
What is the maximum file size ? 
It seems its only 500kb. I want to load files with several gigabytes of size into the pagecache tho.

**Comment by C-Otto** [comment]
Try `./vmtouch -m 100G`

**Comment by maci0** [comment]
wow, that was quick. 
Thanks.
Works fine now. You know by any chance what the hard limit is ?

**Comment by hoytech** [comment]
The default is 500mb. This is mostly because of a limitation on 32-bit platforms. Because vmtouch mmap()s each file, it must be small enough to fit in your virtual memory address space. In other words, this value must fit into a size_t.

On 32-bit platforms the hard limit is 4gb, although mappings that large will likely fail. Realistically it's probably closer to 2gb.

On 64-bit platforms there is essentially no hard limit, or rather the limit will be imposed by your filesystem, not vmtouch. I've considered raising the default on 64-bit platforms.

Cheers,

Doug

**Comment by hoytech** [comment]
As of 1.0.1 there are no artificial limits by default, and you are only bound by the hard limits mentioned above.

The `-m` flag still exists for backwards compatibility and in case you wish to impose an artificially lower limit on yourself for some reason.

Thanks!
