### ISSUE TITLE
vmtouch: FATAL: mlock: archive.org (Cannot allocate memory)

### ISSUE THREAD

**Issue by novoid** [hoytech/vmtouch#18]
Hi!

Did find your tool via http://blog.binchen.org/posts/emacs-speed-up-1000.html and wanted to try it to speed up my Emacs Org-mode file (lock them to RAM).

I have to admit, that I don't know how your tools works in detail tough.

What I got:

```
vk@gary ~/org (git)-[master] % vmtouch -vld *.org                                                                  :(
vmtouch: FATAL: mlock: archive.org (Cannot allocate memory)
vk@gary ~/org (git)-[master] % vmtouch -v *.org
archive.org
[OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO] 37/37
bwg.org
[OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO] 142/142
contacts.org
[OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO] 302/302
errors_orgmode_commits.org
[O] 1/1
foo4.org
[O] 1/1
foo4.org
[OOOOOOOOOOOOOOOOO] 17/17
foodandbeverages.org
[OOOOOOOOOO] 10/10
hardware.org
[OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO] 139/139
inbox.org
[OOO] 3/3
foo4.org
[OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO] 130/130
milhouse_tododb.org
[OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO] 33/33
misc.org
[OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO] 561/561
foo3.org
[OOOOOOOOOOO] 11/11
notes.org
[OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO] 361/361
private.org
[OOOOO] 5/5
foo2.org
[OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO] 78/78
foo1.org
[OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO] 74/74
references.org
[OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO] 135/135
test.org
[OOO] 3/3
vimorganizercheatsheet.org
[OO] 2/2

           Files: 20
     Directories: 0
  Resident Pages: 2045/2045  7M/7M  100%
         Elapsed: 0.002972 seconds
vk@gary ~/org (git)-[master] % 
```

How do I have to interpret this error message?

Is vmtouch not working with my Debian GNU/Linux Wheezy?

**Comment by hoytech** [comment]
Hi, thanks for the link!

The error you are seeing is a result of hitting a resource limit on locked memory:

    $ ls -l file
    -rw-rw-r-- 1 doug doug 100000 May 14 10:47 file
    $ vmtouch -l file 
    vmtouch: FATAL: mlock: file (Cannot allocate memory)

Because locking file pages into memory prevents the OS from paging them out and using them for other purposes, it can be somewhat dangerous if you start to run low on memory (and you are locking a large percentage of your RAM), so the OS by default limits the amount you can lock to a very small amount. You can see how much by running your shell's ulimit built-in:

    $ ulimit -a|grep locked
    max locked memory       (kbytes, -l) 64

Note that as a regular user you cannot raise your ulimit:

    $ ulimit -l 65
    bash: ulimit: max locked memory: cannot modify limit: Operation not permitted

If you wish, you can change the default ulimits for particular users (see the limits.conf man page or docs on cgroups).

However, if you are root, vmtouch will attempt to automatically raise its limit high enough to lock the files you request:

    $ sudo vmtouch -l file 
    LOCKED 25 pages (100K)

Some systems like BSD and older linux kernels also have a system-wide limit on how much memory may be locked, but as of linux 2.6.9 that limit was removed so the resource limit described above should be the only thing.

Thanks for this question, I should add this info to the documentation!

Cheers,

Doug

**Comment by novoid** [comment]
Glad, that my issue was not an error between keyboard and chair :-)

My system has also the 64kB limit set. Glad to have learned about this thing thanks to your great explanation.

However, I do have followup questions:

With 8GB or RAM and 64bit operating systems, this 64kB limit seems to be rather conservative. Is there (still) a good reason for that or is this an historic limitation I can change without negative impact on my system?

Concrete example: Is it wise to set the limit so that I can lock 200MB of Org-mode files and my 250MB of Emacs configuration+external packages in order to get speed-up on my GNU/Linux SSD system?

Also: how "big" would you guess is the advantage of locking via vmtouch on a system with a decent SDD?

Thanks for clearification and thinking about adding those considerations to your documentation as well. On the one side, `vmtouch` is a great tool also for ordinary users. On the other side, the (probably negative) impact could not be foreseen by users without deeper knowledge.

**Comment by hoytech** [comment]
I'm not sure on the exact reasoning behind the 64k default, except note that this is 64k *per process* (plus another 64k for shared memory segments), which can potentially be much larger.

FYI: You can see the total amount of locked memory on your system like so:

    $ grep -i mlock /proc/meminfo 
    Mlocked:             216 kB

Regarding your concrete example, I would say that no, there is nothing wrong with locking that much data in memory, just be aware that 450MB of RAM will be allocated solely for those files and cannot be used for processes or other filesystem cache entries.

If you are randomly accessing these files frequently, and you have fairly high VFS cache pressure, then this may make a big difference. Otherwise, your OS usually does a pretty good job of managing the cache in a "least-recently used" fashion (but of course LRU is not always optimal -- that being one of the purposes of vmtouch). Really the only way to know for sure is to test and see.

An SSD will help a lot versus an HDD by reducing the random access latency, however randomly accessing the filesystem cache is still much faster than an SSD (relatively speaking). Remember that even with an SSD, it is first read into the filesystem cache and then given to your process. Here are some back of the envelope latency numbers you may find interesting:

https://gist.github.com/jboner/2841832

Populating the FS cache from an SSD will also have decreased performance if the SSD is heavily loaded and/or your have very high VFS pressure (for example if you're swapping and you also need to write out pages to free them).

Sorry for such a non-committal answer, but the only truly correct response is "it depends". :)

**Comment by novoid** [comment]
Thanks!

Being an IT guy myself, I am totally aware of the universal nature of "it depends". :-)

**Comment by dotdoom** [comment]
Worth noting that apart from `ulimit` there's also `vm.max_map_count` sysctl that also limits the number of `mmap()`ed files on Linux.

Do you collect any documentation on which tunables are related?

**Comment by hoytech** [comment]
@dotdoom - Good idea, I've started collecting some details here: https://github.com/hoytech/vmtouch/blob/master/TUNING.md

Pull requests for any additional info is much appreciated.

**Comment by dotdoom** [comment]
Awesome, thank you!

**Comment by vladak** [comment]
On Solaris, the memory locked page limit can be set on per-project or per-zone basis, see resource-controls(5) man page for details. The limits can be manipulated and observed using `prctl`  or `zonecfg` command, e.g.:

```
$ prctl -n project.max-locked-memory -i process $$ 
process: 4690: bash
NAME    PRIVILEGE       VALUE    FLAG   ACTION                       RECIPIENT
project.max-locked-memory
        usage               0B   
        system          16.0EB    max   deny                                 -
```

You might want to add it to the `TUNING.md` document.

**Comment by hoytech** [comment]
Thank you! I've updated `TUNING.md`.
