### ISSUE TITLE
Fix release tarball/directory name

### ISSUE THREAD

**Issue by ismail** [hoytech/vmtouch#34]
Currently releases are named like vmtouch-vmtouch-$version.tar.gz and extracts to vmtouch-vmtouch-$version which is kind of weird. They should be named as vmtouch-$version instead.

**Comment by hoytech** [comment]
Ahh interesting, I never noticed that.

I'm used to tagging "product-version" because sometimes you have multiple products in the same repo, but it seems github is expecting just "version". I'll tag the next release with just "version".

There's a couple outstanding PRs that I'm going to get to soon and then I'll release 1.0.3.

Thanks!

**Comment by ismail** [comment]
Thanks a lot!

**Comment by hoytech** [comment]
OK I think I've fixed it. The tarballs now extract to ie "vmtouch-1.1.0":

https://github.com/hoytech/vmtouch/archive/v1.1.0.tar.gz

Unfortunately the tarball's name is v1.1.0.tar.gz, where I'd prefer vmtouch-1.1.0.tar.gz, but this naming convention seems to be standard on other github projects so I guess it's normal.

Thanks again!
